FROM ghcr.io/saleor/saleor:3.20

LABEL ro.surmont.service="api"
LABEL ro.surmont.description="surmontsaleor core contained"

COPY docker/saleor-core/settings.py /app/saleor/settings.py
COPY docker/saleor-core/prices.py /app/saleor/core/prices.py